<script setup>
import {ref,computed} from "vue";
const user=ref(null),login=ref({username:"",password:""}),error=ref(""),admin=ref({teachers:[],groups:[],students:[]}),teacher=ref({groups:[],students:[]}),student=ref({student:null,events:[]}),selected=ref(null),form=ref({name:"",username:"",password:"1234",group_id:"",teacher_id:""});
async function api(u,o={}){const r=await fetch(u,{headers:{"Content-Type":"application/json"},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Server xatosi");return d}
async function refresh(){if(user.value?.role==="admin")admin.value=await api("/api/admin");if(user.value?.role==="teacher")teacher.value=await api("/api/teacher/"+user.value.id);if(user.value?.role==="student")student.value=await api("/api/student/"+user.value.id)}
async function signin(){try{user.value=await api("/api/login",{method:"POST",body:JSON.stringify(login.value)});await refresh()}catch(e){error.value=e.message}}
async function add(kind){try{let u="/api/"+kind,b={name:form.value.name};if(kind==="teachers")Object.assign(b,{username:form.value.username,password:form.value.password});if(kind==="groups")b.teacher_id=form.value.teacher_id||null;if(kind==="students")Object.assign(b,{username:form.value.username,password:form.value.password,group_id:form.value.group_id||null});await api(u,{method:"POST",body:JSON.stringify(b)});form.value.name="";form.value.username="";await refresh()}catch(e){error.value=e.message}}
async function score(s,u,b){await api(u,{method:"POST",body:JSON.stringify(b)});await refresh()}
const students=computed(()=>selected.value?teacher.value.students.filter(s=>s.group_id===selected.value.id):teacher.value.students);
</script>
<template><div class="app">
<div v-if="!user" class="login"><div class="card login-card"><h1>EduScore</h1><p>Vue + PostgreSQL</p><input v-model="login.username" placeholder="Login"><input v-model="login.password" type="password" placeholder="Parol"><button @click="signin">Kirish</button><small>Demo: admin/1234 · anvar/1234 · usmon/1234</small><p class="err">{{error}}</p></div></div>
<template v-else><header><b>EduScore</b><span>{{user.name}} · {{user.role}}</span><button @click="user=null">Chiqish</button></header>
<main v-if="user.role==='admin'"><h2>Admin panel</h2><div class="grid"><section class="card"><h3>Teacher</h3><input v-model="form.name" placeholder="Ism"><input v-model="form.username" placeholder="Login"><input v-model="form.password" placeholder="Parol"><button @click="add('teachers')">Qo'shish</button></section><section class="card"><h3>Group</h3><input v-model="form.name" placeholder="Group nomi"><select v-model="form.teacher_id"><option value="">Teacher</option><option v-for="t in admin.teachers" :value="t.id">{{t.name}}</option></select><button @click="add('groups')">Qo'shish</button></section><section class="card"><h3>Student</h3><input v-model="form.name" placeholder="Ism"><input v-model="form.username" placeholder="Login"><input v-model="form.password" placeholder="Parol"><select v-model="form.group_id"><option value="">Group</option><option v-for="g in admin.groups" :value="g.id">{{g.name}}</option></select><button @click="add('students')">Qo'shish</button></section></div><section class="card"><h3>Ma'lumotlar</h3><div v-for="s in admin.students" class="row"><b>{{s.name}}</b><span>{{s.group_name||'Guruh yo‘q'}}</span><strong>{{s.score}} ball</strong></div></section></main>
<main v-else-if="user.role==='teacher'"><h2>Teacher panel</h2><div class="groups"><button :class="{on:!selected}" @click="selected=null">Barchasi</button><button v-for="g in teacher.groups" :class="{on:selected?.id===g.id}" @click="selected=g">{{g.name}}</button></div><section class="card"><div v-for="s in students" class="student"><div><b>{{s.name}}</b><small>{{s.score}} ball</small></div><div class="actions"><button @click="score(s,'/api/attendance',{student_id:s.id,present:true})">Bor +3</button><button @click="score(s,'/api/attendance',{student_id:s.id,present:false})">Yo'q</button><button @click="score(s,'/api/homework',{student_id:s.id,status:'Bor'})">Uyga +5</button><button @click="score(s,'/api/homework',{student_id:s.id,status:'Chala'})">Chala +3</button><button @click="score(s,'/api/homework',{student_id:s.id,status:'Yo\'q'})">Yo'q +1</button><button @click="score(s,'/api/score',{student_id:s.id,points:Number(prompt('Necha ball?')||0)})">+ Ball</button></div></div></section></main>
<main v-else><h2>Student panel</h2><section class="card big" v-if="student.student"><small>Jami ball</small><strong>{{student.student.score}}</strong><p>{{student.student.name}} · {{student.student.group_name}}</p></section><section class="card"><h3>Ball tarixi</h3><div v-for="e in student.events" class="row"><span>{{e.type}}</span><b>+{{e.points}}</b></div></section></main>
</template></div></template>